{
 "title": "Raid (mdadm)",
 "description": "Prometheus node_exporter mdadm module dashboard. Per Server and per md view",
 "tags": [
  "disk",
  "mdstat"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_md_disks, instance)"
   },
   {
    "name": "host",
    "query": "label_values(node_md_disks{instance=~\"$instance\"}, instance)"
   },
   {
    "name": "md",
    "query": "label_values(node_md_disks{instance=~\"$instance\"}, device)"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All mds are active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_state{state=\"active\", instance=~\"$instance\"}) / count(node_md_state{state=\"active\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "All md disks are active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_disks{instance=~\"$instance\", state=\"active\"}) / sum(node_md_disks{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Active Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_disks{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total installed Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_disks{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total MD RAIDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_md_disks{instance=~\"$instance\",state=\"active\"})"
    }
   ]
  },
  { "title": "RAID $host $md", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "md" },
  {
   "title": "$md is active",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_state{instance=~\"$instance\",device=\"$md\", state=\"active\"}) / count(node_md_state{instance=~\"$instance\",device=\"$md\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "RAID status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_md_state{instance=~\"$instance\",device=\"$md\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Disks status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_md_disks{instance=~\"$instance\",device=\"$md\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Sync time remaining",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_md_sync_time_remaining{instance=~\"$instance\",device=\"$md\"}",
     "legendFormat": "{{device }}"
    },
    {
     "expr": "node_md_sync_time_remaining_seconds{instance=~\"$instance\",device=\"$md\"}",
     "legendFormat": "{{device }}"
    }
   ]
  },
  {
   "title": "Sync rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_md_blocks_synced_speed{instance=~\"$instance\",device=\"$md\"}",
     "legendFormat": "{{device }}"
    }
   ]
  },
  {
   "title": "Sync ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_md_blocks_synced{instance=~\"$instance\",device=\"$md\"} / node_md_blocks{instance=~\"$instance\",device=\"$md\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disks status in $md",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_disks{state=\"active\", instance=~\"$instance\",device=\"$md\"}) / sum(node_md_disks{instance=~\"$instance\",device=\"$md\"})"
    }
   ]
  }
 ]
}