# Фрагменты submodule services.zeroclaw.settings (порядок как в исходном settings.nix)
[
  ./agent.nix
  ./agents.nix
  ./scalar_options.nix
  ./autonomy.nix
  ./backup.nix
  ./browser.nix
  ./browser_delegate.nix
  ./channels_config.nix
  ./cloud_ops.nix
  ./composio.nix
  ./conversational_ai.nix
  ./cost.nix
  ./cron.nix
  ./data_retention.nix
  ./embedding_routes.nix
  ./gateway.nix
  ./google_workspace.nix
  ./hardware.nix
  ./heartbeat.nix
  ./hooks.nix
  ./http_request.nix
  ./identity.nix
  ./knowledge.nix
  ./linkedin.nix
  ./mcp.nix
  ./memory.nix
  ./microsoft365.nix
  ./model_providers.nix
  ./model_routes.nix
  ./multimodal.nix
  ./node_transport.nix
  ./nodes.nix
  ./notion.nix
  ./observability.nix
  ./peripherals.nix
  ./plugins.nix
  ./project_intel.nix
  ./proxy.nix
  ./query_classification.nix
  ./reliability.nix
  ./runtime.nix
  ./scheduler.nix
  ./secrets.nix
  ./security.nix
  ./security_ops.nix
  ./skills.nix
  ./storage.nix
  ./swarms.nix
  ./transcription.nix
  ./tts.nix
  ./tunnel.nix
  ./web_fetch.nix
  ./web_search.nix
  ./workspace.nix
]
